# Generated by Django 3.2.20 on 2023-08-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='classification',
            field=models.CharField(choices=[('News', 'News'), ('Art', 'Art'), ('IB resources', 'Ib')], default='IB resources', max_length=50),
        ),
    ]
