# Generated by Django 3.2.20 on 2023-08-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_webpage_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='classification',
            field=models.CharField(choices=[('News', 'News'), ('Art', 'Art'), ('IB', 'Ib')], default='IB', max_length=50),
        ),
    ]
