# Generated by Django 3.2.20 on 2023-08-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_alter_webpage_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='classification',
            field=models.CharField(choices=[('News', 'News'), ('Art', 'Art'), ('IB', 'Ib'), ('Work', 'Work'), ('Geeks', 'Geeks'), ('Study', 'Study')], default='IB', max_length=50),
        ),
    ]
