# Generated by Django 3.2.20 on 2024-03-02 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0005_alter_webpage_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='webpage',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='classification',
        ),
        migrations.AlterField(
            model_name='webpage',
            name='link',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='webpage',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webpages', to='explore.category'),
        ),
    ]
