# Generated by Django 3.2.20 on 2024-03-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0006_auto_20240302_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
