# Generated by Django 3.2.20 on 2024-03-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0007_webpage_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='category',
        ),
        migrations.AddField(
            model_name='webpage',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='webpages', to='explore.Category'),
        ),
    ]
